### ISSUE TITLE
ImageNotFound is raised when using gulp_image_folder script

### ISSUE THREAD

**Issue by talhadar** [TwentyBN/GulpIO#65]
Hi,

There is a bug in the ImageFolderAdapter.
When i'm using the gulp_image_folder script it raises ImageNotFound error:
`gulpio.utils.ImageNotFound: ('Image read None from path ', '/Users/BBB/Development/Dataset/Gulpio/mnist/training/1/1-1-33918.png')`

I looked into your code and saw that when you parse the folder you set the "id" to be as follow:
`data.append({'id': category_name + '-' + img_name, 'label': category_name, 'path': path})`

The problem when you iterate through the data in `def iter_data(self, slice_element=None)`
is that you concat the img_path to be as follows:
`img_path = os.path.join(str(meta['path']), str(meta['id']))`
the id is not the real image filename because when parsing the folder you concatenating the image name with the category name, so you need to remove the "label" from the "id" before joining the "path" and the "id" into "img_path" since the image doesn't really exists (when concatenating with category_name)

**Comment by esc** [comment]
Hi, thanks for your bug report. Can you provide a pull-request to fix this?

**Comment by talhadar** [comment]
Hi, I created a pull request to fix it
