### ISSUE TITLE
Can Gulp'd data be copied to different drive?

### ISSUE THREAD

**Issue by sawyermade** [TwentyBN/GulpIO#92]
I was just wondering if Gulp'd data could be copied to a different drive and have the same performance, like if the drive had the same read/write performance, or does it have to be Gulp'd on each drive independently?

**Comment by esc** [comment]
@sawyermade yes, the encoding is just a bunch of files on disk and can easily be moved/copied to a different drive.

Note also, that you should be looking at: https://github.com/willprice/GulpIO2 -- since this repo hasn't seen any activity for a long time.

**Comment by sawyermade** [comment]
I thought so but was just making sure. Thanks for the response.
